spring:
  application:
    name: pubgproject

  datasource:
    url: jdbc:mysql://localhost:3306/pubgproject
    username: root
    password: ansxoddl123

  jpa:
    hibernate:
      ddl-auto: update
      use-new-id-generator-mappings: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect